// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetAvailableSkins():Promise<Array<string>>;

export function Startup(arg1:context.Context,arg2:string):Promise<void>;
