// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableSkins() {
    return window["go"]["skin"]["Service"]["GetAvailableSkins"]();
}

export function Startup(arg1, arg2) {
    return window["go"]["skin"]["Service"]["Startup"](arg1, arg2);
}
