// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authorize():Promise<string>;

export function CheckTokens():Promise<boolean>;

export function GenTokens(arg1:string):Promise<void>;

export function GetAccessToken():Promise<string>;

export function RefreshTokens():Promise<void>;
