// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authorize() {
  return window['go']['racetime']['WebRace']['Authorize']();
}

export function CheckTokens() {
  return window['go']['racetime']['WebRace']['CheckTokens']();
}

export function GenTokens(arg1) {
  return window['go']['racetime']['WebRace']['GenTokens'](arg1);
}

export function GetAccessToken() {
  return window['go']['racetime']['WebRace']['GetAccessToken']();
}

export function RefreshTokens() {
  return window['go']['racetime']['WebRace']['RefreshTokens']();
}
