// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {context} from '../models';

export function CloseSplitFile():Promise<void>;

export function GetConfig():Promise<session.Config>;

export function GetLoadedSplitFile():Promise<session.SplitFilePayload>;

export function GetSessionStatus():Promise<session.ServicePayload>;

export function LoadSplitFile():Promise<session.SplitFilePayload>;

export function Pause():Promise<void>;

export function Reset():Promise<void>;

export function Split():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateSplitFile(arg1:session.SplitFilePayload):Promise<boolean>;
