// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSplitFile() {
  return window['go']['session']['Service']['CloseSplitFile']();
}

export function GetConfig() {
  return window['go']['session']['Service']['GetConfig']();
}

export function GetLoadedSplitFile() {
  return window['go']['session']['Service']['GetLoadedSplitFile']();
}

export function GetSessionStatus() {
  return window['go']['session']['Service']['GetSessionStatus']();
}

export function LoadSplitFile() {
  return window['go']['session']['Service']['LoadSplitFile']();
}

export function Pause() {
  return window['go']['session']['Service']['Pause']();
}

export function Reset() {
  return window['go']['session']['Service']['Reset']();
}

export function SaveSplitFile() {
  return window['go']['session']['Service']['SaveSplitFile']();
}

export function Split() {
  return window['go']['session']['Service']['Split']();
}

export function Startup(arg1) {
  return window['go']['session']['Service']['Startup'](arg1);
}

export function UpdateSplitFile(arg1) {
  return window['go']['session']['Service']['UpdateSplitFile'](arg1);
}
