// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {context} from '../models';

export function Load(arg1:string):Promise<void>;

export function Pause():Promise<void>;

export function Reset():Promise<void>;

export function Save(arg1:string,arg2:session.SplitFile):Promise<void>;

export function Split():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
