// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load(arg1) {
  return window['go']['session']['Service']['Load'](arg1);
}

export function Pause() {
  return window['go']['session']['Service']['Pause']();
}

export function Reset() {
  return window['go']['session']['Service']['Reset']();
}

export function Save(arg1, arg2) {
  return window['go']['session']['Service']['Save'](arg1, arg2);
}

export function Split() {
  return window['go']['session']['Service']['Split']();
}

export function Startup(arg1) {
  return window['go']['session']['Service']['Startup'](arg1);
}
