package skin

import (
	"os"
	"path/filepath"

	"github.com/zellydev-games/opensplit/logger"
)

// SaveWorkingCopy persists the current editor working copy to disk.
//
// Saving is intentionally a separate operation from editor mutation.
// Editor changes only modify EditorState. This method is the single
// working-copy -> disk boundary.
//
// The filesystem watcher is suppressed for the writes generated by this
// operation. The editor working copy already contains the state being saved,
// so reloading it from disk would be redundant and would unnecessarily
// replace editor UI state such as the selected element and active rule.
func (s *Service) SaveWorkingCopy() error {
	_, rules, dirty, target, active, revision := s.editor.Snapshot()

	logger.Infof(
		logModule,
		"SaveWorkingCopy: rules=%d dirty=%t revision=%d target=%+v activeRule=%v",
		len(rules),
		dirty,
		revision,
		target,
		active != nil,
	)

	if !dirty {
		logger.Infof(
			logModule,
			"SaveWorkingCopy: working copy is clean; nothing to write",
		)

		return nil
	}

	// Filesystem writes performed below can generate asynchronous watcher
	// events. Suppress those events before starting the write.
	s.suppressSaveWatcherEvents()

	if err := s.saveEditor(); err != nil {
		return err
	}

	// saveEditor clears Dirty but deliberately leaves Target and ActiveRule
	// untouched. Emit that exact current editor state to the frontend.
	if err := s.EmitSkinModel(); err != nil {
		return err
	}

	s.notifySkinUpdated()

	return nil
}

// saveEditor writes the current editor working copy to the selected skin.
//
// CSS and other text files are written using their current working-copy
// contents. CSSFile.Contents is kept synchronized with the parser rule tree
// by the editor mutation methods.
func (s *Service) saveEditor() error {
	files,
		_,
		_,
		_,
		_,
		_ := s.editor.Snapshot()

	root := s.GetSkinPath()

	for _, file := range files {
		if !file.Text {
			continue
		}

		filename := filepath.Join(
			root,
			file.Path,
		)

		if err := os.MkdirAll(
			filepath.Dir(filename),
			0o755,
		); err != nil {
			return err
		}

		logger.Infof(
			logModule,
			"saveEditor: writing %q length=%d",
			filename,
			len(file.Contents),
		)

		if err := os.WriteFile(
			filename,
			[]byte(file.Contents),
			0o644,
		); err != nil {
			return err
		}
	}

	s.editor.ClearDirty()

	return nil
}
