package skin

import (
	"net"
	"net/http"
	"sync"
	"sync/atomic"
	"time"

	"github.com/zellydev-games/opensplit/config"
	"github.com/zellydev-games/opensplit/dto"
	"github.com/zellydev-games/opensplit/repo"
	"github.com/zellydev-games/opensplit/skin/editor"
)

const (
	logModule  = "skins"
	EntryPoint = "index.css"

	// skinSaveWatcherSuppressDuration is the amount of time filesystem
	// watcher events are ignored after an editor save.
	//
	// SaveWorkingCopy can produce filesystem events asynchronously after the
	// files have actually been written. The watcher event observed in
	// practice can arrive several hundred milliseconds after SaveWorkingCopy
	// returns, so this window must be longer than a single filesystem write.
	//
	// ReloadEditor also preserves the current selection, so this suppression
	// is only an optimization that prevents an unnecessary disk reload.
	skinSaveWatcherSuppressDuration = 2 * time.Second
)

// SkinProvider defines the public skin service API exposed to the rest of the
// application.
type SkinProvider interface {
	SetSkin(string, bool) error
	CreateSkin(name string, base string) error

	// Editor navigation.
	SelectElement(string) error
	SelectFile(string) error
	SelectRule(string, string) error
	ClearElement() error

	// Editor mutation.
	UpdateActiveRule(dto.CSSRuleEditor) error
	UpdateFileContents(string, string) error
	SetDefaultLayout(string) error

	// Working copy.
	CreateCSSFile(string) error
	CreateCSSRule(dto.CSSRuleEditor) error
	DeleteCSSRule(string) error

	// Persistence.
	SaveWorkingCopy() error
	ReloadEditor() error

	EmitSkinModel() error

	SelectedSkin() string
	GetAvailableSkins() []string

	SetPreviewElements([]dto.SkinPreviewElement) error
}

// DirectoryWatcher watches a directory for changes.
type DirectoryWatcher interface {
	Start(string, func())
	ChangeRoot(string)
}

// Service manages installed skins, the embedded HTTP server, filesystem
// watching, editor state, and persistence of the selected skin.
type Service struct {
	m sync.RWMutex

	initOnce sync.Once
	initErr  error

	skinDir string

	server   *http.Server
	listener net.Listener

	serving atomic.Bool

	address string
	port    int

	selectedSkin string

	configService *config.Service
	repoService   *repo.Service

	watcher DirectoryWatcher

	skinUpdatedCh chan string
	skinModelCh   chan SkinModel

	editor *editor.EditorState

	// saveWatcherUntil prevents filesystem watcher events generated by
	// SaveWorkingCopy from causing an unnecessary editor reload.
	//
	// SaveWorkingCopy updates the working copy on disk, but EditorState
	// already contains the exact state that was saved. Reloading from disk
	// immediately after saving would unnecessarily replace the editor model
	// and can reset editor UI state.
	saveWatcherUntil time.Time
}

// NewService creates a skin service and its notification channels.
func NewService(
	skinDir string,
	configService *config.Service,
	repoService *repo.Service,
	watcher DirectoryWatcher,
) (*Service, chan string, chan SkinModel) {
	updateCh := make(chan string, 1)
	modelCh := make(chan SkinModel, 1)

	return &Service{
		skinDir: skinDir,

		configService: configService,
		repoService:   repoService,

		watcher: watcher,

		skinUpdatedCh: updateCh,
		skinModelCh:   modelCh,

		editor: editor.NewEditorState(),
	}, updateCh, modelCh
}

// suppressSaveWatcherEvents prevents filesystem watcher events generated by
// the current editor save from reloading the working copy.
func (s *Service) suppressSaveWatcherEvents() {
	s.m.Lock()
	defer s.m.Unlock()

	s.saveWatcherUntil = time.Now().Add(
		skinSaveWatcherSuppressDuration,
	)
}

// shouldSuppressSaveWatcherEvent reports whether a filesystem watcher event
// should be ignored because it was generated by the editor save.
func (s *Service) shouldSuppressSaveWatcherEvent() bool {
	s.m.Lock()
	defer s.m.Unlock()

	if s.saveWatcherUntil.IsZero() {
		return false
	}

	if time.Now().After(s.saveWatcherUntil) {
		s.saveWatcherUntil = time.Time{}

		return false
	}

	return true
}
