// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsRunning() {
  return window['go']['timer']['Service']['IsRunning']();
}

export function Pause() {
  return window['go']['timer']['Service']['Pause']();
}

export function Reset() {
  return window['go']['timer']['Service']['Reset']();
}

export function Run() {
  return window['go']['timer']['Service']['Run']();
}

export function Start() {
  return window['go']['timer']['Service']['Start']();
}

export function Startup(arg1) {
  return window['go']['timer']['Service']['Startup'](arg1);
}
