// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function IsRunning():Promise<boolean>;

export function Pause():Promise<void>;

export function Reset():Promise<void>;

export function Run():Promise<void>;

export function Start():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
