// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dispatch(arg1, arg2) {
  return window['go']['dispatcher']['Service']['Dispatch'](arg1, arg2);
}

export function MapHotkey(arg1, arg2) {
  return window['go']['dispatcher']['Service']['MapHotkey'](arg1, arg2);
}
