// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dispatcher} from '../models';

export function Dispatch(arg1:dispatcher.Command,arg2:any):Promise<dispatcher.DispatchReply>;
