// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dispatch(arg1, arg2) {
  return window['go']['dispatcher']['Service']['Dispatch'](arg1, arg2);
}

export function ExportSplitFile(arg1) {
  return window['go']['dispatcher']['Service']['ExportSplitFile'](arg1);
}

export function OpenSkinsFolder() {
  return window['go']['dispatcher']['Service']['OpenSkinsFolder']();
}

export function OpenSplitFileFolder() {
  return window['go']['dispatcher']['Service']['OpenSplitFileFolder']();
}
