// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {command} from '../models';
import {dispatcher} from '../models';

export function Dispatch(arg1:command.Command,arg2:any):Promise<dispatcher.DispatchReply>;

export function ExportSplitFile(arg1:string):Promise<void>;

export function OpenSkinsFolder():Promise<void>;

export function OpenSplitFileFolder():Promise<void>;
