// tools/gencommands/main.go
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type command struct {
	Name  string
	Value int
}

func main() {
	root, err := findRoot()
	if err != nil {
		panic(err)
	}

	commandDir := filepath.Join(root, "command")

	entries, err := os.ReadDir(commandDir)
	if err != nil {
		panic(err)
	}

	fset := token.NewFileSet()
	var commands []command

	for _, entry := range entries {
		if entry.IsDir() ||
			!strings.HasSuffix(entry.Name(), ".go") ||
			strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		src := filepath.Join(commandDir, entry.Name())

		file, err := parser.ParseFile(fset, src, nil, parser.ParseComments)
		if err != nil {
			panic(err)
		}

		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.CONST {
				continue
			}

			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok || !isCommandType(vs.Type) {
					continue
				}

				if len(vs.Values) != len(vs.Names) {
					panic(fmt.Sprintf(
						"%s: command declaration must have one value per name",
						src,
					))
				}

				for i, name := range vs.Names {
					value, err := constantValue(vs.Values[i])
					if err != nil {
						panic(fmt.Sprintf(
							"%s: %s: %v",
							src,
							name.Name,
							err,
						))
					}

					commands = append(commands, command{
						Name:  name.Name,
						Value: value,
					})
				}
			}
		}
	}

	sort.Slice(commands, func(i, j int) bool {
		if commands[i].Value == commands[j].Value {
			return commands[i].Name < commands[j].Name
		}
		return commands[i].Value < commands[j].Value
	})

	validate(commands)

	var out bytes.Buffer

	fmt.Fprintln(&out, "// Code generated by tools/gencommands. DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "export const Command = {")

	for _, c := range commands {
		fmt.Fprintf(&out, "\t%s: %d,\n", c.Name, c.Value)
	}

	fmt.Fprintln(&out, "} as const;")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "export type Command = typeof Command[keyof typeof Command];")

	dst := filepath.Join(root, "frontend", "src", "models", "command.ts")

	existing, err := os.ReadFile(dst)
	if err == nil && bytes.Equal(existing, out.Bytes()) {
		return
	}

	if err := os.WriteFile(dst, out.Bytes(), 0644); err != nil {
		panic(err)
	}
}

func findRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}

	// `go generate ./command` runs this program with the working
	// directory set to the command package.
	if filepath.Base(wd) == "command" {
		return filepath.Dir(wd), nil
	}

	// Direct invocation from the repository root.
	if _, err := os.Stat(filepath.Join(wd, "command")); err == nil {
		return wd, nil
	}

	return "", fmt.Errorf(
		"could not find repository root from %s",
		wd,
	)
}

func isCommandType(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == "Command"
}

func constantValue(expr ast.Expr) (int, error) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.INT {
		return 0, fmt.Errorf("command value must be an integer literal")
	}

	value, err := strconv.ParseInt(lit.Value, 0, 64)
	if err != nil {
		return 0, fmt.Errorf("invalid integer literal %q: %w", lit.Value, err)
	}

	return int(value), nil
}

func validate(commands []command) {
	names := make(map[string]struct{}, len(commands))
	values := make(map[int]string, len(commands))

	for _, c := range commands {
		if _, exists := names[c.Name]; exists {
			panic(fmt.Sprintf("duplicate command name: %s", c.Name))
		}
		names[c.Name] = struct{}{}

		if previous, exists := values[c.Value]; exists {
			panic(fmt.Sprintf(
				"duplicate command value %d: %s and %s",
				c.Value,
				previous,
				c.Name,
			))
		}
		values[c.Value] = c.Name
	}
}
