// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachHotkeyProvider(arg1) {
  return window['go']['statemachine']['Service']['AttachHotkeyProvider'](arg1);
}

export function Dispatch(arg1, arg2) {
  return window['go']['statemachine']['Service']['Dispatch'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['statemachine']['Service']['Startup'](arg1);
}
