// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {statemachine} from '../models';
import {context} from '../models';

export function Dispatch(arg1:statemachine.Command,arg2:any):Promise<statemachine.DispatchReply>;

export function Startup(arg1:context.Context):Promise<void>;
