// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolder(arg1) {
  return window['go']['sysopen']['Service']['OpenFolder'](arg1);
}

export function OpenSkinsFolder() {
  return window['go']['sysopen']['Service']['OpenSkinsFolder']();
}

export function Startup(arg1) {
  return window['go']['sysopen']['Service']['Startup'](arg1);
}
