// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {context} from '../models';

export function Load():Promise<session.SplitFile>;

export function Save():Promise<void>;

export function SetSplitFile(arg1:session.SplitFile):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
