// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load() {
  return window['go']['persister']['Service']['Load']();
}

export function Save() {
  return window['go']['persister']['Service']['Save']();
}

export function SetSplitFile(arg1) {
  return window['go']['persister']['Service']['SetSplitFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['persister']['Service']['Startup'](arg1);
}
