// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {splits} from '../models';
import {context} from '../models';

export function Load():Promise<splits.SplitFile>;

export function Save():Promise<void>;

export function SetSplitFile(arg1:splits.SplitFile):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
